### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by Andreasdahlberg** [cantools/cantools#384]
**Steps to reproduce:** 
Run `cantools generate_c_source --no-floating-point-numbers --database-name NAME --output-directory OUT_DIR DBC_FILE`

**Output:**
```
Traceback (most recent call last):
  File "/usr/local/bin/cantools", line 5, in <module>
    from cantools.__init__ import _main
  File "/usr/local/lib/python3.8/dist-packages/cantools/__init__.py", line 13, in <module>
    from . import database as db
  File "/usr/local/lib/python3.8/dist-packages/cantools/database/__init__.py", line 8, in <module>
    from . import can
  File "/usr/local/lib/python3.8/dist-packages/cantools/database/can/__init__.py", line 1, in <module>
    from .database import Database
  File "/usr/local/lib/python3.8/dist-packages/cantools/database/can/database.py", line 11, in <module>
    from .formats import arxml
  File "/usr/local/lib/python3.8/dist-packages/cantools/database/can/formats/arxml.py", line 11, in <module>
    from ..signal import Signal, NamedSignalValue
  File "/usr/local/lib/python3.8/dist-packages/cantools/database/can/signal.py", line 5, in <module>
    from cantools.typechecking import Comments
  File "/usr/local/lib/python3.8/dist-packages/cantools/typechecking.py", line 3, in <module>
    import typing_extensions
ModuleNotFoundError: No module named 'typing_extensions'
```

**OS:** Ubuntu 20.04.3 (running on Github Actions)
**Version:** 37.0.2 (installed with pip)

**Comment by juleq** [comment]
@zariiii9003 Can you fix that and add a test that covers it? Thanks.

**Comment by juleq** [comment]
Release is out, please try. Pypi will have it in a few minutes.

**Comment by Andreasdahlberg** [comment]
Works fine now with 37.0.3, thanks!
