### ISSUE TITLE
Getting below error while parsing ARXML file in cantools

### ISSUE THREAD

**Issue by mkchame07** [cantools/cantools#429]
Traceback (most recent call last):
  File "<pyshell#34>", line 1, in <module>
    db = cantools.database.load_file(r"D:\Canoe\P16_CANoe\P16_CANoe\mclaren_adi_p16\McLaren_P16.arxml")
  File "D:\python37\lib\site-packages\cantools\database\__init__.py", line 198, in load_file
    sort_signals)
  File "D:\python37\lib\site-packages\cantools\database\__init__.py", line 290, in load
    sort_signals)
  File "D:\python37\lib\site-packages\cantools\database\__init__.py", line 394, in load_string
    raise UnsupportedDatabaseFormatError(e_arxml, e_dbc, e_kcd, e_sym, e_cdd)
cantools.database.UnsupportedDatabaseFormatError: ARXML: "Cannot retrieve a child element of a non-existing node!"

**Comment by andlaus** [comment]
seems like the arxml code assumes the presence of a tag that is optional. Unfortunately, the backtrace above does not say which. Can you provide an example file with this problem?
