### ISSUE TITLE
TypeError on import/init

### ISSUE THREAD

**Issue by marhmm-ducktrain** [cantools/cantools#475]
Hello,

I get the following error directly after running "import cantools" in a python console running on Kubuntu 22.04, Python 3.10.4:

```
markus@markus-HP-ZBook:~$ python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cantools
Traceback (most recent call last):
  File "/home/markus/.local/lib/python3.10/site-packages/can/interfaces/__init__.py", line 36, in <module>
    entries = entry_points(group="can.interface")
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/markus/.local/lib/python3.10/site-packages/cantools/__init__.py", line 7, in <module>
    from . import tester
  File "/home/markus/.local/lib/python3.10/site-packages/cantools/tester.py", line 7, in <module>
    import can
  File "/home/markus/.local/lib/python3.10/site-packages/can/__init__.py", line 27, in <module>
    from .util import set_logging_level
  File "/home/markus/.local/lib/python3.10/site-packages/can/util.py", line 18, in <module>
    from .interfaces import VALID_INTERFACES
  File "/home/markus/.local/lib/python3.10/site-packages/can/interfaces/__init__.py", line 40, in <module>
    entries = entry_points().get("can.interface", [])
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

cantools Version:

```
pip3 show cantools
Name: cantools
Version: 37.1.2
Summary: CAN BUS tools.
Home-page: https://github.com/eerimoq/cantools
Author: Erik Moqvist
Author-email: erik.moqvist@gmail.com
License: MIT
Location: /home/markus/.local/lib/python3.10/site-packages
Requires: argparse-addons, bitstruct, diskcache, python-can, textparser, typing-extensions
Required-by:
```

Is there anything I am missing?

**Comment by juleq** [comment]
Try uninstalling and reinstalling cantools. Maybe also update pip3. 

FYI: I am on Ubuntu 20.04, Python 3.8.10 and cantools 37.1.2. No issues.

**Comment by juleq** [comment]
Yes, I would assume the Python installation has a problem. Please tell us if fixing that did fix your problem.
