### ISSUE TITLE
Create new empty database

### ISSUE THREAD

**Issue by zorce** [cantools/cantools#546]
Try to create a new empty database, plan is to generate many databases.
But have problems to write a new dbc file. Short testcode

```
import cantools
db = cantools.db
db.Bus('test', baudrate=500000)
cantools.db.dump_file(db, 'test.dbc')
```

But this gives the traceback
```
Traceback (most recent call last):
  File "tmp.py", line 7, in <module>
    cantools.db.dump_file(db, 'test.dbc')
  File "<pythonpath>\site-packages\cantools\database\__init__.py", line 247, in dump_file
    output = database.as_dbc_string(sort_signals=sort_signals)
AttributeError: module 'cantools.database' has no attribute 'as_dbc_string'
```

Maybe not the correct way to do this, and maybe not ment to create databases with this tool?

**Comment by andlaus** [comment]
```python
import cantools
db = cantools.database.Database()
cantools.database.dump_file(db, 'test.dbc')
```

should work
